from __future__ import annotations
from typing import Protocol
from PySide6 import QtGui

class Tool(Protocol):
    """Giao diện chung cho các công cụ vẽ."""
    def on_activate(self): ...
    def on_deactivate(self): ...
    def mousePressEvent(self, e: QtGui.QMouseEvent): ...
    def mouseMoveEvent(self, e: QtGui.QMouseEvent): ...
    def mouseReleaseEvent(self, e: QtGui.QMouseEvent): ...
    def keyPressEvent(self, e: QtGui.QKeyEvent): ...
    # Không bắt buộc, nếu có Canvas sẽ gọi để vẽ preview:
    # def paint_overlay(self, painter: QtGui.QPainter): ...
